{% set name = "djongo" %}
{% set version = "1.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djongo-{{ version }}.tar.gz
  sha256: b4b767174095c06eae2c344f201dc809ffc156b9c99d44ab8f798309090cae29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=2.1,<=3.0.5
    - pymongo >=3.2.0
    - python >=3.6
    - sqlparse 0.2.4

test:
  imports:
    - djongo
    - djongo.dynamic_formsets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nesdis.github.io/djongo/
  summary: Driver for allowing Django to use MongoDB as the database backend.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
